modules:
  - module_type: llama_index_chunk
    chunk_method: Token
    chunk_size: 1024
    chunk_overlap: 24
    add_file_name: en
  - module_type: llama_index_chunk
    chunk_method: Token
    chunk_size: 2048
    chunk_overlap: 48
    add_file_name: en
  - module_type: llama_index_chunk
    chunk_method: SentenceWindow
    sentence_splitter : kiwi
    window_size: 3
    add_file_name: en